language: python
# cache: pip # not enough installed via pip to justify
jobs:
  include:
    # - name: "Python 3.6 on Linux"
    #   python: 3.6
    #   os: linux
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36;/c/Python36/Scripts:$PATH
before_install:
  - pip install -U pip
install: 
  - pip install -r ./ci/requirements.txt
  - pip install -r ./python/requirements.txt
  - ./ci/install_$TRAVIS_OS_NAME.sh
script:
  - ./ci/test.sh
  - ./ci/lint.sh
  - make local_run
