name: Perforce
description: Checks out a perforce repository instead of git.
author: https://github.com/ca-johnson
requirements:
  - p4
configuration:
  properties:
    p4port:
      type: string
    p4user:
      type: string
    p4tickets:
      type: string
    p4trust:
      type: string  
    stream:
      type: string
    view:
      type: string
    root:
      type: string
